#if UNITY_EDITOR
using System;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Phase 16.18 commercial handoff-authority consolidation.
///
/// Phase16.16 added a Root-space provider bridge after the canonical ProviderHub
/// had already gained provider/resume normalization. Both mechanisms are useful
/// in isolation, but enabling both creates two release trajectories for one
/// provider switch.
///
/// Commercial default:
/// - ProviderHub owns provider-space / resume coordinate normalization.
/// - KiwiFaceMotion keeps no-frame hold, static rest and the final discontinuity
///   safety envelope.
/// - The Phase16.16 Root-space provider bridge remains compiled as a fallback
///   only when canonical handoff normalization is disabled.
///
/// r5 migration hardening:
/// - Preserves the Phase16.18 runtime contract.
/// - Uses the actual Phase16.16 accepted-provider state method generated by KiwiPhase16_16ProviderBridgeMigration.
/// - Never references providerChanged before its local declaration.
/// - Repairs the malformed r4 state prelude if encountered after an external source repair.
/// - Does not depend on exact whitespace/line formatting left by older migrations.
/// - Is idempotent and accepts an already-complete Phase16.18 target.
/// </summary>
[InitializeOnLoad]
public static class KiwiPhase16_18SingleHandoffAuthorityMigration
{
    private const string TargetPath =
        "Assets/Script/KiwiFaceMotion.cs";

    private const string Prerequisite16 =
        "KIWI_V5_1_PHASE16_16_ROOT_SPACE_PROVIDER_BRIDGE";

    public const string Marker =
        "KIWI_V5_1_PHASE16_18_SINGLE_HANDOFF_AUTHORITY";

    private const string StateMethodName =
        "HandlePhase16_16AcceptedProviderFrame";

    private const string ApplyMethodName =
        "ApplyPhase16_16ProviderRootBridge";

    private const string EnvelopeMethodName =
        "ApplyPhase16_15RootCorrectionEnvelope";

    private static int _retryCount;

    static KiwiPhase16_18SingleHandoffAuthorityMigration()
    {
        EditorApplication.delayCall += ApplyWhenReady;
    }

    [MenuItem(
        "Tools/Kiwi Avatar System/Apply v5.1 Phase 16.18 Single Handoff Authority")]
    private static void ApplyFromMenu()
    {
        _retryCount = 0;
        ApplyWhenReady();
    }

    private static void ApplyWhenReady()
    {
        if (!File.Exists(TargetPath))
        {
            Retry();
            return;
        }

        string originalDisk =
            File.ReadAllText(TargetPath);

        string source =
            NormalizeNewlines(originalDisk);

        if (HasCompletePatch(source))
        {
            return;
        }

        // Phase16.17 patches Quality10, not KiwiFaceMotion, so this migration
        // must not wait for the Phase16.17 marker inside this file. Preflight
        // independently verifies the single-presentation-authority contract.
        if (!source.Contains(Prerequisite16))
        {
            Retry();
            return;
        }

        bool statePatched =
            PatchProviderBridgeState(ref source);

        bool applicationPatched =
            PatchProviderBridgeApplication(ref source);

        bool envelopePatched =
            PatchFinalEnvelope(ref source);

        if (
            !statePatched ||
            !applicationPatched ||
            !envelopePatched
        )
        {
            Debug.LogError(
                "[KiwiAvatarSystem] Phase16.18 could not safely complete the " +
                "Single Handoff Authority migration. " +
                "State=" + statePatched +
                ", Application=" + applicationPatched +
                ", Envelope=" + envelopePatched +
                ". KiwiFaceMotion was left unchanged. " +
                "This usually means the local cumulative KiwiFaceMotion differs " +
                "from the known Phase16.15/16 method layout.");
            return;
        }

        if (!HasCompletePatch(source))
        {
            Debug.LogError(
                "[KiwiAvatarSystem] Phase16.18 patch failed its final contract check. " +
                "KiwiFaceMotion was left unchanged.");
            return;
        }

        WritePreservingFormat(
            TargetPath,
            originalDisk,
            source);

        AssetDatabase.ImportAsset(
            TargetPath,
            ImportAssetOptions.ForceUpdate);

        Debug.Log(
            "[KiwiAvatarSystem] Phase16.18 Single Handoff Authority applied. " +
            "ProviderHub owns canonical handoff normalization; the Phase16.16 " +
            "Root-space bridge is fallback-only.");
    }

    private static void Retry()
    {
        _retryCount++;

        if (_retryCount <= 24)
        {
            EditorApplication.delayCall +=
                ApplyWhenReady;
        }
    }

    private static bool PatchProviderBridgeState(
        ref string source)
    {
        if (!TryGetMethodRangeByName(
            source,
            StateMethodName,
            out int start,
            out int end))
        {
            return false;
        }

        string method =
            source.Substring(start, end - start);

        // r4 inserted a suppression block at method entry that referenced the
        // providerChanged local before Phase16.16 declared it. Remove only that
        // known malformed block when present. This is deliberately narrow so an
        // unknown/custom local method is never rewritten broadly.
        Regex malformedR4Prelude =
            new Regex(
                @"\s*if\s*\(\s*canonicalHandoffOwner\s*\)\s*\{\s*" +
                @"if\s*\(\s*providerChanged\s*&&\s*phase16_16EnableRootProviderBridge\s*\)\s*\{\s*" +
                @"KiwiPhase16_18HandoffAuthorityDiagnostics\s*\.\s*" +
                @"ReportLocalProviderBridgeSuppressed\s*\(\s*\)\s*;\s*\}\s*" +
                @"if\s*\(\s*_phase16_16ProviderBridgeActive\s*\)\s*\{\s*" +
                @"ResetPhase16_16ActiveBridgeOnly\s*\(\s*\)\s*;\s*\}\s*\}",
                RegexOptions.CultureInvariant | RegexOptions.Singleline);

        if (malformedR4Prelude.IsMatch(method))
        {
            method =
                malformedR4Prelude.Replace(
                    method,
                    string.Empty,
                    1);
        }

        // canonicalHandoffOwner itself is safe to declare at method entry because
        // it does not depend on any later local variable.
        if (!Regex.IsMatch(
            method,
            @"\bbool\s+canonicalHandoffOwner\s*=",
            RegexOptions.CultureInvariant))
        {
            int body =
                method.IndexOf("{", StringComparison.Ordinal);

            if (body < 0)
            {
                return false;
            }

            string ownerDeclaration =
                "\n        // " + Marker + "\n" +
                "        bool canonicalHandoffOwner =\n" +
                "            KiwiTrackingProviderHub.\n" +
                "                CanonicalHandoffNormalizationEnabled;\n";

            method =
                method.Insert(
                    body + 1,
                    ownerDeclaration);
        }
        else if (!method.Contains(Marker))
        {
            int body =
                method.IndexOf("{", StringComparison.Ordinal);

            if (body < 0)
            {
                return false;
            }

            method =
                method.Insert(
                    body + 1,
                    "\n        // " + Marker + "\n");
        }

        Match providerDeclaration =
            Regex.Match(
                method,
                @"\bbool\s+providerChanged\s*=",
                RegexOptions.CultureInvariant);

        if (!providerDeclaration.Success)
        {
            return false;
        }

        Regex guardedStartBranch =
            new Regex(
                @"if\s*\(\s*!canonicalHandoffOwner\s*&&\s*providerChanged\s*&&\s*phase16_16EnableRootProviderBridge\s*\)",
                RegexOptions.CultureInvariant);

        Regex oldStartBranch =
            new Regex(
                @"if\s*\(\s*providerChanged\s*&&\s*phase16_16EnableRootProviderBridge\s*\)",
                RegexOptions.CultureInvariant);

        Match guardedMatch =
            guardedStartBranch.Match(method);

        Match oldMatch =
            oldStartBranch.Match(method);

        int branchIndex =
            guardedMatch.Success
                ? guardedMatch.Index
                : oldMatch.Success
                    ? oldMatch.Index
                    : -1;

        if (
            branchIndex < 0 ||
            branchIndex <= providerDeclaration.Index
        )
        {
            return false;
        }

        // The suppression diagnostic and residual-state reset are inserted only
        // immediately before the original Phase16.16 start branch. At this point
        // providerChanged is already declared by the Phase16.16 method.
        const string suppressionToken =
            "KIWI_V5_1_PHASE16_18_STATE_SUPPRESSION_AFTER_PROVIDER_DECLARATION";

        if (!method.Contains(suppressionToken))
        {
            string prelude =
                "        // " + suppressionToken + "\n" +
                "        if (\n" +
                "            canonicalHandoffOwner &&\n" +
                "            providerChanged &&\n" +
                "            phase16_16EnableRootProviderBridge)\n" +
                "        {\n" +
                "            KiwiPhase16_18HandoffAuthorityDiagnostics.\n" +
                "                ReportLocalProviderBridgeSuppressed();\n" +
                "        }\n\n" +
                "        if (\n" +
                "            canonicalHandoffOwner &&\n" +
                "            _phase16_16ProviderBridgeActive)\n" +
                "        {\n" +
                "            ResetPhase16_16ActiveBridgeOnly();\n" +
                "        }\n\n";

            method =
                method.Insert(
                    branchIndex,
                    prelude);
        }

        if (!guardedStartBranch.IsMatch(method))
        {
            Match match =
                oldStartBranch.Match(method);

            if (!match.Success)
            {
                return false;
            }

            method =
                oldStartBranch.Replace(
                    method,
                    "if (!canonicalHandoffOwner && providerChanged && phase16_16EnableRootProviderBridge)",
                    1);
        }

        providerDeclaration =
            Regex.Match(
                method,
                @"\bbool\s+providerChanged\s*=",
                RegexOptions.CultureInvariant);

        int suppressionIndex =
            method.IndexOf(
                suppressionToken,
                StringComparison.Ordinal);

        Match finalGuardedMatch =
            guardedStartBranch.Match(method);

        if (
            !providerDeclaration.Success ||
            suppressionIndex <= providerDeclaration.Index ||
            !finalGuardedMatch.Success ||
            finalGuardedMatch.Index <= providerDeclaration.Index
        )
        {
            return false;
        }

        source =
            source.Substring(0, start) +
            method +
            source.Substring(end);

        return
            method.Contains(Marker) &&
            method.Contains("CanonicalHandoffNormalizationEnabled") &&
            method.Contains("ReportLocalProviderBridgeSuppressed") &&
            method.Contains(suppressionToken) &&
            guardedStartBranch.IsMatch(method);
    }

    private static bool PatchProviderBridgeApplication(
        ref string source)
    {
        if (!TryGetMethodRangeByName(
            source,
            ApplyMethodName,
            out int start,
            out int end))
        {
            return false;
        }

        string method =
            source.Substring(start, end - start);

        const string guardToken =
            "KiwiTrackingProviderHub.CanonicalHandoffNormalizationEnabled";

        if (!method.Contains(guardToken))
        {
            int body =
                method.IndexOf("{", StringComparison.Ordinal);

            if (body < 0)
            {
                return false;
            }

            string inserted =
                "\n        if (KiwiTrackingProviderHub.CanonicalHandoffNormalizationEnabled)\n" +
                "        {\n" +
                "            if (_phase16_16ProviderBridgeActive)\n" +
                "            {\n" +
                "                ResetPhase16_16ActiveBridgeOnly();\n" +
                "            }\n\n" +
                "            KiwiPhase16_16ProviderBridgeDiagnostics.\n" +
                "                ReportApplied(0f, 0f, 0f);\n" +
                "            return;\n" +
                "        }\n";

            method =
                method.Insert(
                    body + 1,
                    inserted);
        }

        source =
            source.Substring(0, start) +
            method +
            source.Substring(end);

        return
            method.Contains(guardToken) &&
            method.Contains("ReportApplied(0f, 0f, 0f)") &&
            method.Contains("return;");
    }

    private static bool PatchFinalEnvelope(
        ref string source)
    {
        if (!TryGetMethodRangeByName(
            source,
            EnvelopeMethodName,
            out int start,
            out int end))
        {
            return false;
        }

        string method =
            source.Substring(start, end - start);

        // Do not depend on the exact Phase16.15 multiline condition. If the
        // canonical handoff term is not already present, fold it into the local
        // finalEnvelopeActive boolean immediately before the first envelope use.
        if (!method.Contains(
            "KiwiTrackingProviderHub.CanonicalHandoffActive"))
        {
            Match firstEnvelopeUse =
                Regex.Match(
                    method,
                    @"(?m)^[ \t]*if\s*\(\s*finalEnvelopeActive\s*\)",
                    RegexOptions.CultureInvariant);

            if (!firstEnvelopeUse.Success)
            {
                return false;
            }

            string canonicalFold =
                "        finalEnvelopeActive =\n" +
                "            finalEnvelopeActive ||\n" +
                "            KiwiTrackingProviderHub.CanonicalHandoffActive;\n\n";

            method =
                method.Insert(
                    firstEnvelopeUse.Index,
                    canonicalFold);
        }

        if (!method.Contains(
            "ReportHubHandoffEnvelopeGuard("))
        {
            Match firstEnvelopeUse =
                Regex.Match(
                    method,
                    @"(?m)^[ \t]*if\s*\(\s*finalEnvelopeActive\s*\)",
                    RegexOptions.CultureInvariant);

            if (!firstEnvelopeUse.Success)
            {
                return false;
            }

            string report =
                "        KiwiPhase16_18HandoffAuthorityDiagnostics.\n" +
                "            ReportHubHandoffEnvelopeGuard(\n" +
                "                finalEnvelopeActive &&\n" +
                "                KiwiTrackingProviderHub.CanonicalHandoffActive);\n\n";

            method =
                method.Insert(
                    firstEnvelopeUse.Index,
                    report);
        }

        source =
            source.Substring(0, start) +
            method +
            source.Substring(end);

        return
            method.Contains(
                "KiwiTrackingProviderHub.CanonicalHandoffActive") &&
            method.Contains(
                "ReportHubHandoffEnvelopeGuard(");
    }

    private static bool HasCompletePatch(
        string source)
    {
        const string suppressionToken =
            "KIWI_V5_1_PHASE16_18_STATE_SUPPRESSION_AFTER_PROVIDER_DECLARATION";

        if (
            !source.Contains(Marker) ||
            !source.Contains("CanonicalHandoffNormalizationEnabled") ||
            !source.Contains("ReportLocalProviderBridgeSuppressed") ||
            !source.Contains("ReportHubHandoffEnvelopeGuard") ||
            !source.Contains("KiwiTrackingProviderHub.CanonicalHandoffActive") ||
            !source.Contains(suppressionToken)
        )
        {
            return false;
        }

        if (!TryGetMethodRangeByName(
            source,
            StateMethodName,
            out int start,
            out int end))
        {
            return false;
        }

        string method =
            source.Substring(start, end - start);

        Match providerDeclaration =
            Regex.Match(
                method,
                @"\bbool\s+providerChanged\s*=",
                RegexOptions.CultureInvariant);

        Match guardedBranch =
            Regex.Match(
                method,
                @"if\s*\(\s*!canonicalHandoffOwner\s*&&\s*providerChanged\s*&&\s*phase16_16EnableRootProviderBridge\s*\)",
                RegexOptions.CultureInvariant);

        int suppressionIndex =
            method.IndexOf(
                suppressionToken,
                StringComparison.Ordinal);

        return
            providerDeclaration.Success &&
            guardedBranch.Success &&
            suppressionIndex > providerDeclaration.Index &&
            guardedBranch.Index > providerDeclaration.Index;
    }

    private static bool TryGetMethodRangeByName(
        string source,
        string methodName,
        out int start,
        out int end)
    {
        start = -1;
        end = -1;

        if (
            string.IsNullOrEmpty(source) ||
            string.IsNullOrEmpty(methodName)
        )
        {
            return false;
        }

        // Older cumulative migrations changed whitespace/line wrapping in
        // KiwiFaceMotion. Match the declaration semantically instead of using
        // one exact formatted signature string.
        string pattern =
            @"\b(?:private|protected|public|internal)\s+" +
            @"(?:static\s+)?void\s+" +
            Regex.Escape(methodName) +
            @"\s*\(";

        Match declaration =
            Regex.Match(
                source,
                pattern,
                RegexOptions.CultureInvariant);

        if (!declaration.Success)
        {
            return false;
        }

        start =
            declaration.Index;

        int brace =
            source.IndexOf(
                '{',
                declaration.Index + declaration.Length);

        if (brace < 0)
        {
            return false;
        }

        int depth = 0;
        bool inString = false;
        bool inChar = false;
        bool inLineComment = false;
        bool inBlockComment = false;
        bool escape = false;

        for (int i = brace; i < source.Length; i++)
        {
            char c = source[i];
            char next =
                i + 1 < source.Length
                    ? source[i + 1]
                    : '\0';

            if (inLineComment)
            {
                if (c == '\n')
                {
                    inLineComment = false;
                }

                continue;
            }

            if (inBlockComment)
            {
                if (c == '*' && next == '/')
                {
                    inBlockComment = false;
                    i++;
                }

                continue;
            }

            if (!inString && !inChar)
            {
                if (c == '/' && next == '/')
                {
                    inLineComment = true;
                    i++;
                    continue;
                }

                if (c == '/' && next == '*')
                {
                    inBlockComment = true;
                    i++;
                    continue;
                }
            }

            if (escape)
            {
                escape = false;
                continue;
            }

            if ((inString || inChar) && c == '\\')
            {
                escape = true;
                continue;
            }

            if (!inChar && c == '"')
            {
                inString = !inString;
                continue;
            }

            if (!inString && c == '\'')
            {
                inChar = !inChar;
                continue;
            }

            if (inString || inChar)
            {
                continue;
            }

            if (c == '{')
            {
                depth++;
            }
            else if (c == '}')
            {
                depth--;

                if (depth == 0)
                {
                    end =
                        i + 1;

                    if (
                        end < source.Length &&
                        source[end] == '\n')
                    {
                        end++;
                    }

                    return true;
                }
            }
        }

        return false;
    }

    private static string NormalizeNewlines(
        string value)
    {
        return
            (value ?? string.Empty)
            .Replace("\r\n", "\n")
            .Replace("\r", "\n");
    }

    private static void WritePreservingFormat(
        string path,
        string original,
        string normalized)
    {
        bool crlf =
            original.IndexOf("\r\n", StringComparison.Ordinal) >= 0;

        string output =
            crlf
                ? normalized.Replace("\n", "\r\n")
                : normalized;

        File.WriteAllText(
            path,
            output,
            new System.Text.UTF8Encoding(false));
    }
}
#endif
